version: '2'

services:
  mysql:
    image: mysql:latest
    environment:
    - DB_USER=root
    - DB_PASS=P@ssw0rd
    volumes:
    - /home/nguyen/Thesis/Docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

    # postgres:
    # image: postgres:latest
    # environment:
    # - POSTGRES_USER=root
    # - POSTGRES_PASSWORD=P@ssw0rd
    # volumes:
    # - /home/nguyen/Thesis/Docker/postgres:/var/lib/postgres
    # ports:
    # - "5432:5432"